# Generated by Django 4.2.9 on 2024-03-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_userasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(),
        ),
    ]
