# Generated by Django 4.2.11 on 2024-04-22 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_userstockportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
